var a = [
{"Frage":"Was hei&szlig;t 'Implizit'?","Antwort":"Darstellung einer Funktion durch eine implizite Funktionsgleichung, die nicht nach der abh&auml;ngigen Variable aufgel&ouml;st ist. Bsp: Y^2+2Y+x^2=0"},
{"Frage":"Was hei&szlig;t 'Explizit'?","Antwort":"Darstellung einer Funktion in einer Weise, die die direkte Berechnung von Funktionswerten durch die Auswertung eines Ausdrucks erlaubt.Y=x^2+2"},
{'Frage':'Was hei&szlig;t Differential?','Antwort':'Ein Differential bezeichnet in der Analysis den linearen Anteil des Zuwachses einer Variablen oder einer Funktion'},
{'Frage':'Was ist die Analysis?','Antwort':'Die grundlegende Analysis befasst sich mit Grenzwerten von Folgen und Reihen sowie mit Funktionen reeller Zahlen und deren Stetigkeit, Differenzierbarkeit und Integration.'},
{'Frage':'Was ist eine lineare Funktion?','Antwort':'Eine Polynomfunktion höchstens ersten Grades. Das heißt: Eine Gerade im zweidimensionalen Raum.',"Kurz":"Gerade"},
{'Frage':'Was berechnet ein Integral?','Antwort':'Ein Integral berechnet den Flächen/Rauminhalt unter einer oder zwischen mehrerern Funktionen.','Kurz':'Flächen/Rauminhalt berechnen'},
{'Frage':'Was bedeutet "Abbildung"?','Antwort':'Bedeutet dasselbe wie Funktion.'},
{'Frage':'Was ist eine Ableitung?','Antwort':'Die Ableitung ist (nach der Vorstellung von Leibniz) der Proportionalitätsfaktor zwischen verschwindend kleinen (infinitesimalen) Änderungen des Eingabewertes und den daraus resultierenden, ebenfalls infinitesimalen Änderungen des Funktionswertes.'},
{"Frage":"Was bedeutet infinitesimal?","Antwort":"etwas, das unendlich klein wird; in der Mathematik etwas, das gegen Null strebt","Kurz":"Unendlich","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{'Frage':'Was sind reele Zahlen?','Antwort':''},
{'Frage':'Was sind nat&uuml;rliche Zahlen?','Antwort':''},
{'Frage':'Was bedeutet "Differenzierbar"?','Antwort':''},
{'Frage':'Was ist ein Exponent?','Antwort':''},
{'Frage':'Was ist eine Potenz?','Antwort':''},
{'Frage':'Was sagt der Logarithmus aus?','Antwort':''},
{'Frage':'Was ist die Abszisse?','Antwort':''},
{'Frage':'Was hei&szlig;t "Disjunctiv"?','Antwort':''},
{'Frage':'Was hei&szlig;t &auml;quivalenzumformung?','Antwort':''},
{'Frage':'Was ist eine Asymptote?','Antwort':''},
{'Frage':'Was ist die Basis?','Antwort':''},
{'Frage':'Was ist ein Binom?','Antwort':''},
{'Frage':'Was ist die Binominalverteilung?','Antwort':''},
{'Frage':'Was hei&szlig;t "Beschr&auml;nkt" im Rahmen einer Funktion?','Antwort':''},
{'Frage':'Was hei&szlig;t "Bestimmt" bei einem Integral / Differential?','Antwort':''},
{'Frage':'Was ist ein Vektor?','Antwort':''},
{'Frage':'Was hei&szlig;t Bijektiv?','Antwort':''},
{'Frage':'Was ist ein Binominalkoeffizient?','Antwort':''},
{'Frage':'Was hei&szlig;t "Diskret"?','Antwort':''},
{'Frage':'Was ist das Bogenma&szlig;?','Antwort':''},
{'Frage':'Was ist eine Definitionsl&uuml;cke?','Antwort':''},
{'Frage':'Was ist der dekadische Logarithmus?','Antwort':''},
{'Frage':'Wie lautet die Regel von l\'Hospital?','Antwort':''},
{'Frage':'Was ist der Differentialquotient?','Antwort':''},
{'Frage':'Was ist ein Intervall?','Antwort':''},
{'Frage':'Was ist eine Dimension?','Antwort':''},
{'Frage':'Was hei&szlig;t Disjunkt?','Antwort':''},
{'Frage':'Was hei&szlig;t Konjunkt?','Antwort':''},
{'Frage':'Was ist das Distributivgesetz?','Antwort':''},
{'Frage':'Was ist der Dyadische Logarithmus?','Antwort':''},
{'Frage':'Was ist eine Konvention?','Antwort':''},
{'Frage':'Was ist die Zahl e ?','Antwort':''},
{'Frage':'Was ist der Einheitsvektor?','Antwort':''},
{'Frage':'Was ist die Eulersche Zahl?','Antwort':''},
{'Frage':'Was ist die Exponentialfunktion?','Antwort':''},
{'Frage':'Was ist ein Extremum?','Antwort':''},
{'Frage':'Was ist eine Nebenbedingung?','Antwort':''},
{'Frage':'Was ist die Fakult&auml;t?','Antwort':''},
{'Frage':'Was ist ein Fraktal?','Antwort':''},
{'Frage':'Was ist eine Funktion?','Antwort':''},
{'Frage':'Was ist ein Polynom?','Antwort':''},
{'Frage':'Was sind ganze Zahlen?','Antwort':''},
{'Frage':'Was ist eine Gau&szlig;-Funktion?','Antwort':''},
{'Frage':'Was ist eine gebrochen rationale Funktion?','Antwort':''},
{'Frage':'Was hei&szlig;t Gleichm&auml;chtig?','Antwort':''},
{'Frage':'Was hei&szlig;t Grad eines Polynoms?','Antwort':''},
{"Frage":"Was ist eine Tangentensteigung?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Frage":"Was ist eine Sekantensteigung?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},

{"Frage":"Was ist ein Index?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]}
]