var a = [
{"Tag":[""],"Frage":"Was ist der CCD Wandler?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Wie sieht eine einzelne Zelle innerhalb eines CCD Wandlers aus?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was ist eine Potentialsenke beim CCD Bildwandler?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was sind Potentialbarrieren?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Wie funktioniert der Ladungstransport (CCD)?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was ist ein Shift-register?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was ist ein Read-Out-Gate?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was ist der FT-CCD?","Antwort":"","Kurz":"Frame-Transfer CCD","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was ist das Interlace Verfahren?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was ist eine Umlaufblende?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was ist der Interlinetransfer?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was ist der Smear-Effekt?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was ist der FIT-CCD?","Antwort":"","Kurz":"Frame-Interline-Transfer CCD","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was ist ein Progressiv-Scan?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was ist die Lens-On-Chip-technologie?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was ist der CMOS?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was sind die Vorteile eines CMOS Sensor?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was ist eine Shutter Funktion?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]}
]
