var a = [
{"Tag":["Signal"],"Frage":"Was ist ein Sample?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":["Signal"],"Frage":"Was ist der Hold?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":["Signal"],"Frage":"Was ist die Puls-Amplituden-Modulation?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":["Signal"],"Frage":"Was ist das Shannon-Abtast-Theorem?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":["Signal"],"Frage":"Was ist die Samplefrequenz?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":["Signal"],"Frage":"Was sind Quantisierungsstufen?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":["Signal"],"Frage":"Was ist das Y-Signal?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Wie funktioniert Farbsampling in digitalen videosignalen?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"Was ist farbsampling?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]}
]