var a =[
{"Tag":["Farbe"],"Frage":"Wie setzen sich die Prim‰rfarben Cyan , Magenta, und Gelb zusammen?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":["Farbe"],"Frage":"Was heiﬂt aditiv?","Antwort":"","Kurz":"rgb gemischt","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":["Farbe"],"Frage":"Was heiﬂt subtraktiv?","Antwort":"","Kurz":"cmy gemischt","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":["Farbe"],"Frage":"Was ist die V-Lambda Kurve","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":["Farbe","Signal"],"Frage":"Was ist das Komponentensignal?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":["Farbe","Signal"],"Frage":"Was ist das Luminanzsignal?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":["Signal"],"Frage":"Was ist ein Farbdifferenzsignal?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":["Signal"],"Frage":"Was ist das Burst Signal?","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":["Farbe","Signal"],"Frage":"Was ist das FBAS Signal?","Antwort":"","Kurz":"Farb-Bild-Austast-Signal","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]},
{"Tag":[""],"Frage":"","Antwort":"","Kurz":"","Befehl":"","Bild":"","FalscheAntwort":["","",""]}
]